-- Add all GPW companies from Stooq
-- ON CONFLICT DO NOTHING: skip existing tickers, never overwrite

INSERT INTO companies (ticker, name, sector, market, has_subsidiaries) VALUES
-- A
('AAT',  'Alta SA',                    'Finance',        'GPW', FALSE),
('ABE',  'AB SA',                      'Technology',     'GPW', TRUE),
('ABS',  'Asseco Business Solutions',  'Technology',     'GPW', FALSE),
('ACG',  'AC SA',                      'Automotive',     'GPW', FALSE),
('ALL',  'Ailleron SA',                'Technology',     'GPW', FALSE),
('ANR',  'Answear.com SA',             'Retail',         'GPW', FALSE),
('APE',  'APS Energy SA',              'Energy',         'GPW', FALSE),
('APN',  'Aplisens SA',                'Manufacturing',  'GPW', FALSE),
('ARL',  'Arlen SA',                   'Other',          'GPW', FALSE),
('ART',  'Artifex Mundi SA',           'Gaming',         'GPW', FALSE),
('ASB',  'ASBIS Enterprises',          'Technology',     'GPW', FALSE),
('ASE',  'Asseco SEE',                 'Technology',     'GPW', TRUE),
('ASM',  'ASM Group SA',               'Manufacturing',  'GPW', FALSE),
('AST',  'Astarta Holding',            'Agriculture',    'GPW', TRUE),
('ATC',  'Arctic Paper SA',            'Manufacturing',  'GPW', TRUE),
('ATD',  'Atende SA',                  'Technology',     'GPW', FALSE),
('ATP',  'Atlanta Poland SA',          'FMCG',           'GPW', FALSE),
('ATR',  'Atrem SA',                   'Construction',   'GPW', FALSE),
('ATS',  'Atlantis SA',                'Other',          'GPW', FALSE),
('AWM',  'Airway Medix SA',            'Healthcare',     'GPW', FALSE),
-- B
('BBD',  'BBi Development SA',         'RealEstate',     'GPW', FALSE),
('BBT',  'BoomBit SA',                 'Gaming',         'GPW', FALSE),
('BCM',  'Betacom SA',                 'Technology',     'GPW', FALSE),
('BCX',  'Bioceltix SA',               'Biotech',        'GPW', FALSE),
('BCS',  'Big Cheese Studio SA',       'Gaming',         'GPW', FALSE),
('BFT',  'Benefit Systems SA',         'Services',       'GPW', FALSE),
('BIO',  'Bioton SA',                  'Pharma',         'GPW', TRUE),
('BIP',  'Bioplanet SA',               'Biotech',        'GPW', FALSE),
('BMC',  'Bumech SA',                  'Mining',         'GPW', FALSE),
('BMX',  'BioMaxima SA',               'Healthcare',     'GPW', FALSE),
('BOS',  'Bank Ochrony Środowiska',    'Banking',        'GPW', FALSE),
('BOW',  'Bowim SA',                   'Manufacturing',  'GPW', FALSE),
('BRS',  'Boryszew SA',                'Manufacturing',  'GPW', TRUE),
-- C
('CAP',  'Capitea SA',                 'Finance',        'GPW', FALSE),
('CAV',  'Cavatina Holding SA',        'RealEstate',     'GPW', TRUE),
('CBF',  'Cyberfolks SA',              'Technology',     'GPW', FALSE),
('CDL',  'CDRL SA',                    'Retail',         'GPW', FALSE),
('CEZ',  'CEZ',                        'Energy',         'GPW', TRUE),
('CIG',  'CI Games SA',                'Gaming',         'GPW', TRUE),
('CLC',  'Columbus Energy SA',         'Energy',         'GPW', FALSE),
('CLD',  'Cloud Technologies SA',      'Technology',     'GPW', FALSE),
('CLE',  'Coal Energy SA',             'Energy',         'GPW', FALSE),
('CLN',  'CLN Pharma SA',              'Pharma',         'GPW', FALSE),
('CMP',  'Comp SA',                    'Technology',     'GPW', FALSE),
('COG',  'Cognor SA',                  'Manufacturing',  'GPW', FALSE),
('CPD',  'Celtic Property Dev.',       'RealEstate',     'GPW', FALSE),
('CPI',  'CPI Europe SA',              'RealEstate',     'GPW', TRUE),
('CPL',  'Comperia.pl SA',             'Finance',        'GPW', FALSE),
('CPR',  'Compremum SA',               'Technology',     'GPW', FALSE),
('CRJ',  'Creepy Jar SA',              'Gaming',         'GPW', FALSE),
('CRM',  'Cormay SA',                  'Healthcare',     'GPW', FALSE),
('CSR',  'Caspar Asset Management',    'Finance',        'GPW', FALSE),
('CTX',  'Captor Therapeutics SA',     'Biotech',        'GPW', FALSE),
-- D
('DAD',  'Dadelo SA',                  'Retail',         'GPW', FALSE),
('DBE',  'DB Energy SA',               'Energy',         'GPW', FALSE),
('DCR',  'Decora SA',                  'Manufacturing',  'GPW', FALSE),
('DEK',  'Dekpol SA',                  'Construction',   'GPW', FALSE),
('DEL',  'Delko SA',                   'Automotive',     'GPW', FALSE),
('DGA',  'DGA SA',                     'Services',       'GPW', FALSE),
('DGE',  'Dragon Energy SA',           'Energy',         'GPW', FALSE),
('DIA',  'Diag SA',                    'Healthcare',     'GPW', FALSE),
('DIG',  'Digitanet SA',               'Technology',     'GPW', FALSE),
('DTR',  'Digitree Group SA',          'Technology',     'GPW', FALSE),
-- E
('EAH',  'Esotiq & Henderson SA',      'Retail',         'GPW', FALSE),
('ECB',  'ECB SA',                     'Finance',        'GPW', FALSE),
('EKP',  'Elkop SE',                   'Other',          'GPW', FALSE),
('ELT',  'Eltrox SA',                  'Manufacturing',  'GPW', FALSE),
('ENE',  'Enel-Med SA',                'Healthcare',     'GPW', FALSE),
('ENI',  'Energoinstal SA',            'Construction',   'GPW', FALSE),
('ENT',  'Enter Air SA',               'Aviation',       'GPW', FALSE),
('EQU',  'Equnico SA',                 'Other',          'GPW', FALSE),
('ERG',  'ERG SA',                     'Manufacturing',  'GPW', FALSE),
('ETL',  'Eurotel SA',                 'Telecom',        'GPW', FALSE),
('EUR',  'Eurocash SA',                'Retail',         'GPW', TRUE),
-- F
('FAB',  'Fabrity Holding SA',         'Technology',     'GPW', FALSE),
('FEE',  'Feerum SA',                  'Manufacturing',  'GPW', FALSE),
('FHB',  'Foodhub SA',                 'Technology',     'GPW', FALSE),
('FON',  'Fonon SA',                   'Technology',     'GPW', FALSE),
('FRO',  'Ferro SA',                   'Manufacturing',  'GPW', FALSE),
('FSG',  'Fasing SA',                  'Manufacturing',  'GPW', FALSE),
-- G
('GIF',  'GameFactor SA',              'Gaming',         'GPW', FALSE),
('GKI',  'Immobile SA',                'RealEstate',     'GPW', TRUE),
('GMT',  'Genomtec SA',                'Biotech',        'GPW', FALSE),
('GRN',  'Grodno SA',                  'Technology',     'GPW', FALSE),
('GRX',  'GreenX SA',                  'Energy',         'GPW', FALSE),
('GTN',  'Getin Noble Bank',           'Banking',        'GPW', FALSE),
('GVT',  'Virtus SA',                  'Other',          'GPW', FALSE),
-- H
('HDR',  'Hydrotor SA',                'Manufacturing',  'GPW', FALSE),
('HEL',  'Helio SA',                   'Food',           'GPW', FALSE),
('HRS',  'Herkules SA',                'Construction',   'GPW', FALSE),
-- I
('ICE',  'Medinice SA',                'Healthcare',     'GPW', FALSE),
('IFI',  'iFirma SA',                  'Technology',     'GPW', FALSE),
('IMP',  'Imperio SA',                 'RealEstate',     'GPW', FALSE),
('IMS',  'IMS SA',                     'Technology',     'GPW', FALSE),
('INC',  'INC SA',                     'Finance',        'GPW', FALSE),
('INL',  'Introl SA',                  'Technology',     'GPW', FALSE),
('INP',  'Inpro SA',                   'RealEstate',     'GPW', FALSE),
('IPE',  'Ipopema Securities SA',      'Finance',        'GPW', FALSE),
('ITB',  'Interbud-Lublin SA',         'Construction',   'GPW', FALSE),
('IZO',  'Izolacja-Jarocin SA',        'Manufacturing',  'GPW', FALSE),
('IZS',  'Izostal SA',                 'Manufacturing',  'GPW', FALSE),
-- J
('JRH',  'JRH SA',                     'Other',          'GPW', FALSE),
-- K
('KCI',  'KCI SA',                     'RealEstate',     'GPW', FALSE),
('KGH',  'KGHM Polska Miedź',          'Mining',         'GPW', TRUE),
('KMP',  'Kompap SA',                  'Manufacturing',  'GPW', FALSE),
('KOM',  'Komputronik SA',             'Retail',         'GPW', FALSE),
('KPL',  'Kinopol SA',                 'Media',          'GPW', FALSE),
('KRK',  'Krka SA',                    'Pharma',         'GPW', TRUE),
('KSG',  'KSG Agro SA',                'Agriculture',    'GPW', FALSE),
-- L
('LBT',  'Libet SA',                   'Manufacturing',  'GPW', FALSE),
('LBW',  'Lubawa SA',                  'Manufacturing',  'GPW', FALSE),
('LEN',  'Lena Lighting SA',           'Manufacturing',  'GPW', FALSE),
('LES',  'Less SA',                    'Other',          'GPW', FALSE),
('LKD',  'Lokum Deweloper SA',         'RealEstate',     'GPW', FALSE),
('LRQ',  'LARQ SA',                    'Finance',        'GPW', FALSE),
('LSI',  'LSI Software SA',            'Technology',     'GPW', FALSE),
('LTX',  'Lentex SA',                  'Manufacturing',  'GPW', FALSE),
-- M
('MCI',  'MCI Capital SA',             'Finance',        'GPW', FALSE),
('MDI',  'MDI Energia SA',             'Energy',         'GPW', FALSE),
('MEX',  'Mex Polska SA',              'Food',           'GPW', FALSE),
('MFO',  'MFO SA',                     'Manufacturing',  'GPW', FALSE),
('MGT',  'Mangata Holding SA',         'Manufacturing',  'GPW', TRUE),
('MIR',  'Miraculum SA',               'FMCG',           'GPW', FALSE),
('MLG',  'MLP Group SA',               'RealEstate',     'GPW', TRUE),
('MLK',  'Milkiland SA',               'Food',           'GPW', TRUE),
('MLS',  'ML System SA',               'Technology',     'GPW', FALSE),
('MNC',  'Mennica Polska SA',          'Manufacturing',  'GPW', FALSE),
('MOC',  'Molecure SA',                'Biotech',        'GPW', FALSE),
('MOJ',  'MOJ SA',                     'Manufacturing',  'GPW', FALSE),
('MOV',  'Movie Games SA',             'Gaming',         'GPW', FALSE),
('MRB',  'MoBruk SA',                  'Environment',    'GPW', FALSE),
('MSP',  'Mostostal Płock SA',         'Construction',   'GPW', FALSE),
('MSW',  'Mostostal Warszawa SA',      'Construction',   'GPW', FALSE),
('MSZ',  'Mostostal Zabrze SA',        'Construction',   'GPW', FALSE),
('MUR',  'Murapol SA',                 'RealEstate',     'GPW', TRUE),
('MVP',  'Marvipol Development SA',    'RealEstate',     'GPW', FALSE),
('MZA',  'Muza SA',                    'Media',          'GPW', FALSE),
-- N
('NCL',  'Noctiluca SA',               'Biotech',        'GPW', FALSE),
('NNG',  'Nanogroup SA',               'Technology',     'GPW', FALSE),
('NTT',  'NTT System SA',              'Technology',     'GPW', FALSE),
('NVA',  'Panova SA',                  'Other',          'GPW', FALSE),
('NVG',  'NovaVis Group SA',           'Technology',     'GPW', FALSE),
('NXG',  'Nexity SA',                  'RealEstate',     'GPW', FALSE),
-- O
('ODL',  'Odlewnie Polskie SA',        'Manufacturing',  'GPW', FALSE),
('ONO',  'OneSano SA',                 'Healthcare',     'GPW', FALSE),
('OND',  'Onde SA',                    'Construction',   'GPW', FALSE),
('OPN',  'Oponeo.pl SA',               'Retail',         'GPW', FALSE),
('OPM',  'OpTeam SA',                  'Technology',     'GPW', FALSE),
('OTS',  'OT Logistics SA',            'Logistics',      'GPW', TRUE),
-- P
('PAS',  'Passus SA',                  'Technology',     'GPW', FALSE),
('PAT',  'Patentus SA',                'Manufacturing',  'GPW', FALSE),
('PBX',  'Pekabex SA',                 'Construction',   'GPW', FALSE),
('PCE',  'Grupa Azoty Police SA',      'Chemicals',      'GPW', FALSE),
('PCR',  'PCC Rokita SA',              'Chemicals',      'GPW', FALSE),
('PEN',  'Photon Energy SA',           'Energy',         'GPW', FALSE),
('PEP',  'PEP SA',                     'Energy',         'GPW', FALSE),
('PGM',  'PMPG Polskie Media SA',      'Media',          'GPW', FALSE),
('PGV',  'PGF Group SA',               'Healthcare',     'GPW', TRUE),
('PHR',  'Pharmena SA',                'Pharma',         'GPW', FALSE),
('PJP',  'PJP Makrum SA',              'Manufacturing',  'GPW', FALSE),
('PLZ',  'Plaza Centers SA',           'RealEstate',     'GPW', FALSE),
('PPS',  'Pepees SA',                  'Food',           'GPW', FALSE),
('PRI',  'Pragma Inkaso SA',           'Finance',        'GPW', FALSE),
('PRM',  'Prochem SA',                 'Construction',   'GPW', FALSE),
('PRT',  'Protektor SA',               'Manufacturing',  'GPW', FALSE),
('PTG',  'Poltreg SA',                 'Healthcare',     'GPW', FALSE),
('PTW',  'PTWP SA',                    'Media',          'GPW', FALSE),
('PUR',  'Pure Biologics SA',          'Biotech',        'GPW', FALSE),
('PWX',  'Polwax SA',                  'Manufacturing',  'GPW', FALSE),
-- Q
('QNA',  'QNA Technology SA',          'Technology',     'GPW', FALSE),
('QRS',  'Quercus TFI SA',             'Finance',        'GPW', FALSE),
-- R
('RLP',  'Relpol SA',                  'Manufacturing',  'GPW', FALSE),
('RMK',  'Remak-Energomontaż SA',      'Construction',   'GPW', FALSE),
('RND',  'Render Frames SA',           'Technology',     'GPW', FALSE),
('RNK',  'Rank Progress SA',           'RealEstate',     'GPW', FALSE),
('RPC',  'Ropczyce SA',                'Manufacturing',  'GPW', FALSE),
('RWL',  'Rawlplug SA',                'Manufacturing',  'GPW', FALSE),
-- S
('SCP',  'SCP Fundusz SA',             'Finance',        'GPW', FALSE),
('SEK',  'Seko SA',                    'Manufacturing',  'GPW', FALSE),
('SEL',  'Selena FM SA',               'Manufacturing',  'GPW', TRUE),
('SFS',  'Sfinks Polska SA',           'Food',           'GPW', FALSE),
('SGN',  'Sygnity SA',                 'Technology',     'GPW', FALSE),
('SIM',  'SimFabric SA',               'Gaming',         'GPW', FALSE),
('SKA',  'Śnieżka SA',                 'Manufacturing',  'GPW', FALSE),
('SKH',  'Skarbiec Holding SA',        'Finance',        'GPW', FALSE),
('SKL',  'Skyline Investment SA',      'RealEstate',     'GPW', FALSE),
('SNT',  'Synektik SA',                'Healthcare',     'GPW', FALSE),
('SNW',  'Sanwil Holding SA',          'Manufacturing',  'GPW', FALSE),
('SNX',  'Sunex SA',                   'Energy',         'GPW', FALSE),
('SON',  'Sonel SA',                   'Manufacturing',  'GPW', FALSE),
('STP',  'Stalprodukt SA',             'Manufacturing',  'GPW', FALSE),
('STF',  'Stalprofil SA',              'Manufacturing',  'GPW', FALSE),
('SVE',  'SNT Verse SA',               'Technology',     'GPW', FALSE),
('SWG',  'Seco/Warwick SA',            'Manufacturing',  'GPW', FALSE),
-- T
('TAR',  'Tarczyński SA',              'Food',           'GPW', FALSE),
('TLX',  'Talex SA',                   'Technology',     'GPW', FALSE),
('TOA',  'Toya SA',                    'Manufacturing',  'GPW', FALSE),
('TRN',  'Transpol SA',                'Logistics',      'GPW', FALSE),
('TSG',  'Tesgas SA',                  'Construction',   'GPW', FALSE),
-- U
('UCG',  'UniCredit',                  'Banking',        'GPW', TRUE),
('ULG',  'Ula Games SA',               'Gaming',         'GPW', FALSE),
('ULM',  'ULMA Construccion Polska',   'Construction',   'GPW', FALSE),
('UNF',  'Unfold SA',                  'Technology',     'GPW', FALSE),
('UNT',  'Unimot SA',                  'Energy',         'GPW', FALSE),
('URT',  'UR Testing SA',              'Services',       'GPW', FALSE),
-- V
('VGO',  'Vigophotonics SA',           'Technology',     'GPW', FALSE),
('VIN',  'Vindexus SA',                'Finance',        'GPW', FALSE),
('VOT',  'Votum SA',                   'Finance',        'GPW', FALSE),
('VVD',  'Vivid Games SA',             'Gaming',         'GPW', FALSE),
-- W
('WAS',  'Wasko SA',                   'Technology',     'GPW', FALSE),
('WIK',  'Wikana SA',                  'RealEstate',     'GPW', FALSE),
('WPR',  'Wood & Company',             'Finance',        'GPW', FALSE),
('WXF',  'Warimpex SA',                'RealEstate',     'GPW', FALSE),
-- X
('XPL',  'X-Plus SA',                  'Other',          'GPW', FALSE),
('XTP',  'XTPL SA',                    'Technology',     'GPW', FALSE),
-- Y
('YAN',  'Yanosik SA',                 'Technology',     'GPW', FALSE),
('YRL',  'Yarly SA',                   'Other',          'GPW', FALSE),
-- Z
('ZRE',  'Zremb-Chojnice SA',          'Manufacturing',  'GPW', FALSE),
('ZUE',  'ZUE SA',                     'Construction',   'GPW', FALSE),
('ZUK',  'Stąporków SA',               'Manufacturing',  'GPW', FALSE),
-- Numeryczne / pozostałe
('06N',  '06 Magna SA',                'Manufacturing',  'GPW', FALSE),
('3RG',  '3R Games SA',                'Gaming',         'GPW', FALSE),
('4MS',  '4Mass SA',                   'Technology',     'GPW', FALSE),
('APT',  'Apator SA',                  'Manufacturing',  'GPW', FALSE),
('GPW',  'GPW SA',                     'Finance',        'GPW', FALSE),
('IMC',  'IMC SA',                     'Agriculture',    'GPW', TRUE)

ON CONFLICT (ticker) DO NOTHING;
